[package]
name = "sonr-tungstenite"
version = "0.1.0"
authors = ["Jonas Hagstedt <hagstedt@gmail.com>"]
edition = "2018"

[dependencies]
sonr = {git = "https://github.com/hagsteel/sonr.git"}
sonr_tls = {git = "https://github.com/hagsteel/sonr-tls.git"}
tungstenite = "0.6.1"
